/*
# Create Coupons and Coupon Usages Tables
Adds the necessary tables and RLS policies for the discount coupon system.

## Query Description:
This operation creates two new tables (`coupons` and `coupon_usages`) and adds missing columns (`discount_amount`, `subtotal`, `coupon_id`) to the existing `orders` table. It does not delete or modify existing data, making it a safe structural update.

## Metadata:
- Schema-Category: "Structural"
- Impact-Level: "Low"
- Requires-Backup: false
- Reversible: true

## Structure Details:
- New table: `public.coupons`
- New table: `public.coupon_usages`
- Altered table: `public.orders` (added `discount_amount`, `subtotal`, `coupon_id`)

## Security Implications:
- RLS Status: Enabled on new tables
- Policy Changes: Yes (added policies for clients and stores to read/write coupons)
- Auth Requirements: Authenticated users only
*/

-- Tabela de cupons
CREATE TABLE IF NOT EXISTS public.coupons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('fixed', 'percentage')),
  value NUMERIC(10,2) NOT NULL,
  min_order_value NUMERIC(10,2) NOT NULL DEFAULT 0,
  max_uses INTEGER DEFAULT NULL,
  max_uses_per_user INTEGER NOT NULL DEFAULT 1,
  store_id BIGINT NOT NULL REFERENCES public.stores(id) ON DELETE CASCADE,
  created_by UUID NOT NULL REFERENCES auth.users(id),
  starts_at TIMESTAMPTZ DEFAULT NULL,
  expires_at TIMESTAMPTZ DEFAULT NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Tabela de usos de cupom
CREATE TABLE IF NOT EXISTS public.coupon_usages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  coupon_id BIGINT NOT NULL REFERENCES public.coupons(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id),
  order_id BIGINT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  used_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Habilitar RLS
ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coupon_usages ENABLE ROW LEVEL SECURITY;

-- Políticas coupons
DO $$ BEGIN
  -- Clientes leem cupons ativos da loja onde estão comprando
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'clientes_leem_cupons' AND tablename = 'coupons') THEN
    CREATE POLICY "clientes_leem_cupons" ON coupons
      FOR SELECT USING (is_active = true);
  END IF;

  -- Loja gerencia seus próprios cupons
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'loja_gerencia_cupons' AND tablename = 'coupons') THEN
    CREATE POLICY "loja_gerencia_cupons" ON coupons
      FOR ALL USING (
        EXISTS (SELECT 1 FROM stores WHERE stores.id = store_id AND stores.owner_id = auth.uid())
      );
  END IF;

  -- Clientes registram uso de cupom
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'clientes_usam_cupons' AND tablename = 'coupon_usages') THEN
    CREATE POLICY "clientes_usam_cupons" ON coupon_usages
      FOR INSERT WITH CHECK (user_id = auth.uid());
  END IF;

  -- Qualquer autenticado lê contagem de usos (para validação)
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'todos_leem_coupon_usages' AND tablename = 'coupon_usages') THEN
    CREATE POLICY "todos_leem_coupon_usages" ON coupon_usages
      FOR SELECT USING (auth.role() = 'authenticated');
  END IF;
END $$;

-- Coluna discount_amount em orders (caso não exista)
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS discount_amount NUMERIC(10,2) NOT NULL DEFAULT 0;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS subtotal NUMERIC(10,2);
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS coupon_id BIGINT REFERENCES public.coupons(id) DEFAULT NULL;
