/*
  # Integração Asaas Connect + Split + Saque Automático
*/

-- Subconta e chave PIX das lojas
ALTER TABLE public.stores
  ADD COLUMN IF NOT EXISTS asaas_wallet_id TEXT,
  ADD COLUMN IF NOT EXISTS asaas_account_id TEXT,
  ADD COLUMN IF NOT EXISTS pix_key TEXT;

-- Subconta e chave PIX dos motoboys (pix_key já existe)
ALTER TABLE public.couriers
  ADD COLUMN IF NOT EXISTS asaas_wallet_id TEXT,
  ADD COLUMN IF NOT EXISTS asaas_account_id TEXT;

-- Tabela de pagamentos
CREATE TABLE IF NOT EXISTS public.payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  asaas_payment_id TEXT,
  method TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  amount NUMERIC(10,2) NOT NULL,
  pix_qr_code TEXT,
  pix_copy_paste TEXT,
  pix_expiration TIMESTAMPTZ,
  split_store_amount NUMERIC(10,2),
  split_platform_amount NUMERIC(10,2),
  split_courier_amount NUMERIC(10,2),
  confirmed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "cliente_ve_pagamento" ON public.payments
  FOR SELECT TO authenticated
  USING (
    EXISTS (SELECT 1 FROM public.orders o WHERE o.id = order_id AND o.client_id = auth.uid())
  );

CREATE POLICY "service_gerencia_pagamentos" ON public.payments
  FOR ALL TO service_role USING (true);

-- Status de pagamento no pedido
ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS payment_status TEXT DEFAULT 'pending';

NOTIFY pgrst, 'reload schema';
