/*
  # Create Product Categories Table
  Creates the product_categories table for store menus and sets up RLS.

  ## Query Description:
  This operation creates the product_categories table, adds the category_id column to the products table, and sets up RLS policies. It is safe to run and will not affect existing data if the tables already exist.
  
  ## Metadata:
  - Schema-Category: "Structural"
  - Impact-Level: "Medium"
  - Requires-Backup: false
  - Reversible: true
  
  ## Structure Details:
  - Creates table `product_categories`
  - Adds column `category_id` to `products`
  
  ## Security Implications:
  - RLS Status: Enabled
  - Policy Changes: Yes (Public Read, Owner All)
  - Auth Requirements: Authenticated for writes
*/

CREATE TABLE IF NOT EXISTS public.product_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT REFERENCES public.stores(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    sort_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.product_categories ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'product_categories' AND policyname = 'Public read access for product_categories'
    ) THEN
        CREATE POLICY "Public read access for product_categories" 
            ON public.product_categories FOR SELECT 
            USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'product_categories' AND policyname = 'Store owners can manage their product_categories'
    ) THEN
        CREATE POLICY "Store owners can manage their product_categories" 
            ON public.product_categories FOR ALL 
            USING (
                auth.uid() IN (
                    SELECT owner_id FROM public.stores WHERE id = store_id
                )
            );
    END IF;
END $$;

-- Add category_id to products if it doesn't exist
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'products' AND column_name = 'category_id') THEN
        ALTER TABLE public.products ADD COLUMN category_id BIGINT REFERENCES public.product_categories(id) ON DELETE SET NULL;
    END IF;
END $$;
