/*
  # Push Notifications — tokens e histórico de envios
*/

-- Tokens FCM de cada dispositivo
CREATE TABLE IF NOT EXISTS public.push_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  token TEXT NOT NULL,
  platform TEXT NOT NULL DEFAULT 'android', -- 'android' | 'ios' | 'web'
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id, token)
);

ALTER TABLE public.push_tokens ENABLE ROW LEVEL SECURITY;

CREATE POLICY "usuario_gerencia_proprio_token" ON public.push_tokens
  FOR ALL TO authenticated USING (user_id = auth.uid());

CREATE POLICY "service_ve_tokens" ON public.push_tokens
  FOR SELECT TO service_role USING (true);

-- Notificações criadas pelo admin e loja
CREATE TABLE IF NOT EXISTS public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_by UUID NOT NULL REFERENCES auth.users(id),
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  target_type TEXT NOT NULL DEFAULT 'all',
  -- 'all' | 'clients' | 'stores' | 'couriers' | 'city'
  target_city TEXT,
  -- se target_type = 'city', filtra por cidade
  store_id BIGINT REFERENCES public.stores(id),
  -- se criado por loja, vincula à loja
  coupon_id BIGINT REFERENCES public.coupons(id),
  -- se vinculado a um cupom
  status TEXT NOT NULL DEFAULT 'pending',
  -- 'pending' | 'sent' | 'scheduled' | 'failed'
  scheduled_at TIMESTAMPTZ,
  -- null = envio imediato
  repeat_type TEXT,
  -- null | 'daily' | 'weekly'
  repeat_day INTEGER,
  -- 0=domingo ... 6=sábado (para weekly)
  repeat_hour INTEGER DEFAULT 18,
  -- hora do envio repetido
  sent_count INTEGER DEFAULT 0,
  sent_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "admin_gerencia_notificacoes" ON public.notifications
  FOR ALL TO authenticated
  USING (auth_role() = 'admin');

CREATE POLICY "loja_cria_notificacao_cupom" ON public.notifications
  FOR INSERT TO authenticated
  WITH CHECK (
    store_id = (SELECT id FROM public.stores WHERE owner_id = auth.uid() LIMIT 1)
  );

CREATE POLICY "loja_ve_proprias_notificacoes" ON public.notifications
  FOR SELECT TO authenticated
  USING (
    store_id = (SELECT id FROM public.stores WHERE owner_id = auth.uid() LIMIT 1)
    OR auth_role() = 'admin'
  );

NOTIFY pgrst, 'reload schema';
